services:
  rdpserver:
    build: .
    image: remote-web-view-server:latest
    container_name: remote-web-view-server
    restart: unless-stopped
    environment:
      VIEWPORT_W: 480
      VIEWPORT_H: 480
      TILE: 32
      FULLFRAME_EVERY: 50
      WS_PORT: 8081
      DEBUG_PORT: 9222
      HEALTH_PORT: 18080
      USER_DATA_DIR: /pw-data
      DEVICE_MAP_JSON: >
        [
          { "id": "living-room", "url": "http://172.16.0.252:8123/dashboard-mobile/0" },
          { "id": "master-bedroom", "url": "http://172.16.0.252:8123/dashboard-mobile/1" }
        ]
    # ports:
    #   - "8081:8081"   # WebSocket для ESP32
    #   - "9222:9222"   # remote DevTools для дебагу з Windows
    # expose:
    #   - "18080"
    volumes:
      - /opt/volumes/esp32-rdp/pw-data:/pw-data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:18080 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    # devices:
    #   - "/dev/dri:/dev/dri"
    